// Regenerates lib/closures/seasonal_gate_lines.g.dart from OpenStreetMap.
//
// For each curated seasonal gate this queries Overpass for the road's OSM
// ways (by ref or name) inside a hand-set bbox approximating the closed
// section, thins the geometry, and emits const polylines keyed by gate id.
// Run whenever seasonal_gates.dart gains a gate:
//
//   dart run tool/fetch_gate_lines.dart
//
// Network is needed at generation time only; the app ships the baked file.
// Geometry © OpenStreetMap contributors (ODbL).
import 'dart:convert';
import 'dart:io';

import 'thin.dart';

// Gate id -> (bbox "south,west,north,east", Overpass way filter). The bbox
// doubles as the clip: ways of the same road outside the closed section are
// excluded by it.
const queries = <String, (String, String)>{
  // 天狗山ゲート～渋峠～陽坂 (both sides of the pass)
  'r292-shibu': ('36.615,138.46,36.71,138.60', '["highway"]["ref"="292"]'),
  // 茅野市北山～麦草峠～小海町
  'r299-mugikusa': ('36.00,138.26,36.10,138.46', '["highway"]["ref"="299"]'),
  // 丸沼～金精トンネル～日光湯元
  'r120-konsei': ('36.75,139.32,36.85,139.44', '["highway"]["ref"="120"]'),
  // 平湯峠～畳平
  'gifu5-norikura-skyline': (
    '36.10,137.48,36.18,137.62',
    '["highway"]["name"~"乗鞍スカイライン"]'
  ),
  // 三本滝～畳平 (OSM tags the road 乗鞍岳線 ref=84; bbox ends at 三本滝 so
  // the always-open valley stretch below stays out)
  'nagano84-norikura-echoline': (
    '36.09,137.55,36.14,137.65',
    '["highway"]["ref"="84"]'
  ),
};

const _overpass = 'https://overpass-api.de/api/interpreter';
const _minSpacingM = 25.0; // thin points closer together than this

Future<void> main() async {
  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/fetch_gate_lines.dart - do not edit.')
    ..writeln('// OSM road geometry for the curated seasonal gates\' closed')
    ..writeln('// sections. © OpenStreetMap contributors (ODbL).')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'package:latlong2/latlong.dart';")
    ..writeln()
    ..writeln('const seasonalGateLines = <String, List<List<LatLng>>>{');

  final client = HttpClient();
  var total = 0;
  for (final entry in queries.entries) {
    final (bbox, filter) = entry.value;
    final query = '[out:json][timeout:60];way$filter($bbox);out geom;';
    final body = await _fetchWithRetry(client, entry.key, query);
    if (body == null) {
      exitCode = 1;
      return;
    }
    final elements = ((jsonDecode(body) as Map)['elements'] as List);
    final lines = <List<(double, double)>>[
      for (final way in elements)
        thinPoints([
          for (final n in (way as Map)['geometry'] as List)
            ((n['lat'] as num).toDouble(), (n['lon'] as num).toDouble()),
        ], _minSpacingM),
    ]..removeWhere((l) => l.length < 2);
    if (lines.isEmpty) {
      stderr.writeln('${entry.key}: no ways matched - check filter/bbox');
      exitCode = 1;
      return;
    }
    final points = lines.fold(0, (n, l) => n + l.length);
    total += points;
    stdout.writeln('${entry.key}: ${lines.length} ways, $points points');

    buf.writeln("  '${entry.key}': [");
    for (final line in lines) {
      buf.write('    [');
      buf.write(line
          .map((p) =>
              'LatLng(${p.$1.toStringAsFixed(5)}, ${p.$2.toStringAsFixed(5)})')
          .join(', '));
      buf.writeln('],');
    }
    buf.writeln('  ],');
    // Be polite to the shared Overpass instance.
    await Future<void>.delayed(const Duration(seconds: 2));
  }
  client.close();

  buf.writeln('};');
  File('lib/closures/seasonal_gate_lines.g.dart')
      .writeAsStringSync(buf.toString());
  stdout.writeln('total $total points -> lib/closures/seasonal_gate_lines.g.dart');
}

/// The public Overpass instance 504s intermittently under load (it keeps
/// only a couple of query slots per IP), so retry with backoff. GET with
/// dart:io - form POSTs have also drawn 504s from its gateway.
Future<String?> _fetchWithRetry(
    HttpClient client, String label, String query) async {
  for (var attempt = 1; attempt <= 5; attempt++) {
    final req = await client.getUrl(
        Uri.parse('$_overpass?data=${Uri.encodeQueryComponent(query)}'));
    req.headers.set('User-Agent', 'rindo-gate-lines/1.0');
    final res = await req.close();
    final body = await res.transform(utf8.decoder).join();
    if (res.statusCode == 200) return body;
    stderr.writeln('$label: Overpass ${res.statusCode} (attempt $attempt)');
    if (res.statusCode != 429 && res.statusCode != 504) break;
    await Future<void>.delayed(Duration(seconds: 10 * attempt));
  }
  return null;
}

