// Regenerates lib/jma/forecast_areas.g.dart: 5-digit municipality code ->
// (JMA class10 forecast subdivision, JMA office), so a map position can be
// turned into the two codes the forecast endpoints are keyed by.
//
//   dart run tool/prep_forecast_areas.dart
//
// JMA publishes forecasts per *office* (58 of them, roughly one per
// prefecture but with Hokkaido split seven ways and Kagoshima/Okinawa split
// too - so no arithmetic on the JIS code gets you there). Within an office's
// file the weather text is broken down by *class10* subdivision (千葉県 ->
// 北西部/北東部/南部), which is what makes the report worth showing: a rider
// in south Chiba should not be reading Chiba city's forecast.
//
// JMA's own area.json carries the hierarchy, but keyed by area codes rather
// than coordinates - so this walks class20 -> class15 -> class10 -> office and
// pins each step to the municipality table's office coordinates, which is the
// position data the app already has. Lookup at runtime is then
// nearest-municipality (see jma_forecast.dart).
//
// class20 codes are the 5-digit JIS code plus '00'. Ward-level rows (札幌市
// 中央区 and the other 政令指定都市 wards) have no class20 of their own -
// JMA stops at the parent city - so they drop out here; the parent city sits
// at practically the same coordinates, so nearest-municipality still lands on
// the right area.
//
// Network needed at generation time only. Rerun if JMA reorganises its
// forecast areas (rare) or after municipal mergers.
import 'dart:convert';
import 'dart:io';

import 'package:rindo/hazards/municipalities.g.dart';

const _source = 'https://www.jma.go.jp/bosai/common/const/area.json';

/// Names come from JMA, not from us - a stray apostrophe (Ho'ou, O'shima)
/// would otherwise close the generated string literal.
String _escape(String s) => s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

Future<void> main() async {
  final client = HttpClient();
  final req = await client.getUrl(Uri.parse(_source));
  final res = await req.close();
  if (res.statusCode != 200) {
    stderr.writeln('area.json: HTTP ${res.statusCode}');
    exitCode = 1;
    return;
  }
  final area = jsonDecode(await res.transform(utf8.decoder).join()) as Map;
  client.close();

  final class20s = area['class20s'] as Map;
  final class15s = area['class15s'] as Map;
  final class10s = area['class10s'] as Map;
  final offices = area['offices'] as Map;

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/prep_forecast_areas.dart - do not edit.')
    ..writeln('// JMA forecast area hierarchy (source: JMA area.json).')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// 5-digit municipality code -> (class10 subdivision, office,')
    ..writeln('/// subdivision name in English, municipality name in English).')
    ..writeln("/// Codes index JMA's forecast/overview_forecast endpoints; the")
    ..writeln("/// names are JMA's own English, which beats machine-translating")
    ..writeln('/// 北東部 into something a rider has to guess at.')
    ..writeln('const forecastAreas = <String, (String, String, String, String)>{');

  var n = 0;
  final skipped = <String>[];
  // Sorted so a regeneration produces a reviewable diff, not a reshuffle.
  for (final code5 in municipalities.keys.toList()..sort()) {
    final class20 = '${code5}00';
    final c20 = class20s[class20];
    if (c20 == null) {
      skipped.add(code5);
      continue;
    }
    final c15 = class15s['${c20['parent']}'];
    final c10 = c15 == null ? null : class10s['${c15['parent']}'];
    final office = c10 == null ? null : '${c10['parent']}';
    if (c10 == null || office == null || !offices.containsKey(office)) {
      skipped.add(code5);
      continue;
    }
    // enName is occasionally missing; the Japanese is a better fallback than
    // a blank, and the sheet shows whatever it's given.
    final areaEn = _escape('${c10['enName'] ?? c10['name']}');
    final townEn = _escape('${c20['enName'] ?? c20['name']}');
    buf.writeln(
      "  '$code5': ('${c15['parent']}', '$office', '$areaEn', '$townEn'),",
    );
    n++;
  }
  buf.writeln('};');

  File('lib/jma/forecast_areas.g.dart').writeAsStringSync(buf.toString());
  stdout.writeln('$n municipalities -> lib/jma/forecast_areas.g.dart');
  stdout.writeln(
    '${skipped.length} without a JMA class20 (wards / post-merger drift)',
  );
}
