// Regenerates lib/map/japan_outline.g.dart from a prefectures GeoJSON.
//
// The outline renders beneath the map tiles as a loading skeleton: while
// tiles are still downloading (or the network is gone) the rider still sees
// the shape of Japan and the prefecture borders instead of a blank void.
//
//   dart run tool/prep_japan_outline.dart [path/to/japan_prefectures.geojson]
//
// Rings are thinned to ~800 m point spacing and specks (tiny islets) are
// dropped - at the zooms where tiles are missing, finer detail is invisible
// anyway. The source file is NOT checked in; pass its path when regenerating.
import 'dart:convert';
import 'dart:io';

import 'thin.dart';

const _defaultSource =
    '../hebberd.com/tools/data/japan_prefectures.geojson';
const _minSpacingM = 800.0;
const _minRingPoints = 6; // after thinning; drops islet specks

void main(List<String> args) {
  final path = args.isNotEmpty ? args.first : _defaultSource;
  final doc = jsonDecode(File(path).readAsStringSync()) as Map;

  final rings = <List<(double, double)>>[];
  var kept = 0, droppedSpecks = 0;
  for (final f in doc['features'] as List) {
    final g = (f as Map)['geometry'] as Map;
    final polys = g['type'] == 'MultiPolygon'
        ? (g['coordinates'] as List)
        : [g['coordinates']];
    for (final poly in polys) {
      for (final ring in poly as List) {
        final thinned = thinPoints([
          for (final pt in ring as List)
            ((pt[1] as num).toDouble(), (pt[0] as num).toDouble()),
        ], _minSpacingM);
        if (thinned.length < _minRingPoints) {
          droppedSpecks++;
          continue;
        }
        rings.add(thinned);
        kept += thinned.length;
      }
    }
  }

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/prep_japan_outline.dart - do not edit.')
    ..writeln('// Prefecture boundary rings (thinned), drawn beneath the map')
    ..writeln('// tiles as a loading skeleton.')
    ..writeln('//')
    ..writeln('// Boundary data: Global Map Japan (地球地図日本, © 国土地理院/GSI,')
    ..writeln('// gsi.go.jp/kankyochiri/gm_jpn.html) via dataofjapan/land.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'package:latlong2/latlong.dart';")
    ..writeln()
    ..writeln('const japanOutline = <List<LatLng>>[');
  for (final ring in rings) {
    buf.write('  [');
    buf.write(ring
        .map((p) =>
            'LatLng(${p.$1.toStringAsFixed(4)}, ${p.$2.toStringAsFixed(4)})')
        .join(', '));
    buf.writeln('],');
  }
  buf.writeln('];');

  File('lib/map/japan_outline.g.dart')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(buf.toString());
  stdout.writeln('${rings.length} rings, $kept points '
      '($droppedSpecks specks dropped) -> lib/map/japan_outline.g.dart');
}

