// Regenerates lib/hazards/municipalities.g.dart: 5-digit municipality code
// -> (name, lat, lon), used to place JMA landslide-alert (土砂災害警戒情報)
// markers - the JMA feed keys by municipality, not by coordinates.
//
//   dart run tool/prep_municipalities.dart
//
// Source: code4fukui/localgovjp (public municipality table with office
// coordinates). Network needed at generation time only. Rerun after big
// municipal mergers (they're rare); alerts for codes missing from the baked
// table are skipped rather than crashing.
import 'dart:convert';
import 'dart:io';

const _source = 'https://code4fukui.github.io/localgovjp/localgovjp.json';

Future<void> main() async {
  final client = HttpClient();
  final req = await client.getUrl(Uri.parse(_source));
  final res = await req.close();
  if (res.statusCode != 200) {
    stderr.writeln('localgovjp: HTTP ${res.statusCode}');
    exitCode = 1;
    return;
  }
  final rows =
      jsonDecode(await res.transform(utf8.decoder).join()) as List;
  client.close();

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/prep_municipalities.dart - do not edit.')
    ..writeln('// Municipality office coordinates (source: localgovjp).')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// 5-digit municipality code -> (name, lat, lon).')
    ..writeln('const municipalities = <String, (String, double, double)>{');
  var n = 0;
  for (final r in rows) {
    final cid = '${r['cid']}'.padLeft(5, '0');
    final name = r['city'];
    final lat = double.tryParse('${r['lat']}');
    final lon = double.tryParse('${r['lng']}');
    if (lat == null || lon == null) continue;
    buf.writeln("  '$cid': ('$name', "
        '${lat.toStringAsFixed(5)}, ${lon.toStringAsFixed(5)}),');
    n++;
  }
  buf.writeln('};');
  File('lib/hazards/municipalities.g.dart')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(buf.toString());
  stdout.writeln('$n municipalities -> lib/hazards/municipalities.g.dart');
}
